# Generated by Django 2.0 on 2019-03-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0003_auto_20190309_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='static/images'),
        ),
    ]
